on: [push, pull_request]

env:
  CONAN_OPTIONS: "*:shared=True,icu:data_packaging=library"
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

jobs:
  MinGW:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingwVersion: ["8"]
        buildType: [Release]
        arch: [x86, x86_64]
        threads: [posix]
        include:
          - arch: "x86"
            exceptions: dwarf2
          - arch: "x86_64"
            exceptions: seh
    steps:
      - name: Disable autocrlf
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install
        run: |
          conan-shared-scripts\install_conan.bat
      - name: build
        env:
          CONAN_BUILD_TYPES: ${{matrix.buildType}}
          MINGW_CONFIGURATIONS: ${{matrix.mingwVersion}}@${{matrix.arch}}@${{matrix.exceptions}}@${{matrix.threads}}
        run: |
          python conan-shared-scripts/build.py --shared icu
